# Generated by Django 3.1.1 on 2020-10-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('short_name', models.CharField(max_length=50, verbose_name='nombre_corto')),
                ('anulate', models.BooleanField(default=False, verbose_name='anulado')),
            ],
        ),
    ]
