# Generated by Django 3.1.1 on 2020-10-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('2', 'ECONOMISTA'), ('4', 'OTRO'), ('1', 'INGENIERO'), ('0', 'CONTADOR'), ('3', 'ADMINISTRADOR')], max_length=1, verbose_name='trabajo'),
        ),
    ]
