# Generated by Django 3.1.1 on 2020-10-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20201002_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('2', 'ECONOMISTA'), ('3', 'ADMINISTRADOR'), ('0', 'CONTADOR'), ('1', 'INGENIERO'), ('4', 'OTRO')], max_length=1, verbose_name='trabajo'),
        ),
    ]
