# Generated by Django 3.1.1 on 2020-10-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20201009_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('1', 'INGENIERO'), ('3', 'ADMINISTRADOR'), ('0', 'CONTADOR'), ('4', 'OTRO'), ('2', 'ECONOMISTA')], max_length=1, verbose_name='trabajo'),
        ),
    ]
